[package]
name = "polkadot-statement-table"
version = "0.8.29"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
parity-scale-codec = { version = "2.0.0", default-features = false, features = ["derive"] }
sp-core = { git = "https://github.com/romanb/substrate", branch = "libp2p-0.36" }
primitives = { package = "polkadot-primitives", path = "../primitives" }
