[package]
name = "polkadot-erasure-coding"
version = "0.8.29"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
primitives = { package = "polkadot-primitives", path = "../primitives" }
novelpoly = { package = "reed-solomon-novelpoly", version = "=0.0.3" }
parity-scale-codec = { version = "2.0.0", default-features = false, features = ["std", "derive"] }
sp-core = { git = "https://github.com/tomaka/polkadot", branch = "refactor-handler" }
trie = { package = "sp-trie", git = "https://github.com/tomaka/polkadot", branch = "refactor-handler" }
thiserror = "1.0.23"
